version: "3.8"

services:
  goals:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:80
    volumes:
      - ./:/app
    environment:
      - MONGO_URL=${MONGO_GOALS_URL}
